# Generated by Django 2.0 on 2017-12-06 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20171206_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choce_text',
            new_name='choice_text',
        ),
    ]
